import React, { useEffect, useState } from 'react';
import { BookOpen, ExternalLink, Sparkles } from 'lucide-react';
import { PageMasthead } from '../components/layout/PageMasthead';

const faqs = [
  {
    question: 'What was Ambedkar’s role in drafting the Constitution?',
    answer: 'B. R. Ambedkar chaired the Constituent Assembly’s Drafting Committee. In that role, he helped present and defend the draft Constitution during Assembly debates.',
    source: 'Constitution of India — B. R. Ambedkar',
    url: 'https://www.constitutionofindia.net/members/b-r-ambedkar/',
  },
  {
    question: 'When did the Constituent Assembly first meet?',
    answer: 'The Constituent Assembly met for the first time on 9 December 1946. It held 167 sitting days over nearly three years while framing the Constitution.',
    source: 'Constitution of India — Constituent Assembly Debates',
    url: 'https://www.constitutionofindia.net/constitution-assembly-debates/',
  },
  {
    question: 'What was the Mahad Satyagraha?',
    answer: 'In 1927, Ambedkar led a protest at Mahad asserting Dalits’ right to draw water from the Chavdar public tank, challenging caste-based exclusion.',
    source: 'Constitution of India — B. R. Ambedkar',
    url: 'https://www.constitutionofindia.net/members/b-r-ambedkar/',
  },
  {
    question: 'What changed under the Poona Pact?',
    answer: 'The 1932 agreement replaced separate electorates for the Depressed Classes with reserved seats in provincial legislatures.',
    source: 'Constitution of India — B. R. Ambedkar',
    url: 'https://www.constitutionofindia.net/members/b-r-ambedkar/',
  },
  {
    question: 'When was the Constitution adopted?',
    answer: 'The Constituent Assembly adopted the Constitution on 26 November 1949. Ambedkar’s Assembly address that day emphasized that its success depended on how it was administered.',
    source: 'Constitution of India — Assembly debate, 26 November 1949',
    url: 'https://www.constitutionofindia.net/debates/26-nov-1949/',
  },
];

export const ResearchPage: React.FC = () => {
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [visibleLength, setVisibleLength] = useState(0);
  const selectedFaq = faqs[selectedIndex];

  useEffect(() => {
    const timer = window.setInterval(() => {
      setVisibleLength((length) => {
        if (length >= selectedFaq.answer.length) {
          window.clearInterval(timer);
          return length;
        }
        return length + 2;
      });
    }, 16);
    return () => window.clearInterval(timer);
  }, [selectedFaq.answer]);

  return (
    <div className="min-h-screen bg-newsprint-100 text-ink">
      <PageMasthead
        eyebrow="ARCHIVE GUIDE • FREQUENTLY ASKED QUESTIONS"
        headline="Explore the archive guide"
        subheadline="Choose a question to see a concise, source-linked answer. Responses below are curated FAQs, not generated by an AI model."
        accession="SOURCE-LINKED FAQ"
        badge="PROTOTYPE GUIDE"
      />
      <main className="mx-auto max-w-5xl space-y-8 px-4 py-8 sm:px-6">
        <section className="grid gap-5 md:grid-cols-[0.9fr_1.1fr]">
          <div className="space-y-3">
            <h2 className="font-serif text-xl font-semibold">Frequently asked questions</h2>
            <div className="space-y-2">
              {faqs.map((faq, index) => (
                <button
                  key={faq.question}
                  type="button"
                  aria-pressed={selectedIndex === index}
                  onClick={() => {
                    if (index !== selectedIndex) {
                      setVisibleLength(0);
                      setSelectedIndex(index);
                    }
                  }}
                  className={`w-full rounded-lg border px-4 py-3 text-left text-sm leading-relaxed transition duration-200 ${
                    selectedIndex === index
                      ? 'border-oxblood bg-[#F5E8E8] text-ink shadow-sm'
                      : 'border-ink/15 bg-white hover:border-ink/30 hover:bg-[#FAF8F3]'
                  }`}
                >
                  {faq.question}
                </button>
              ))}
            </div>
          </div>

          <article className="flex min-h-64 flex-col rounded-xl border border-ink/15 bg-white p-5 shadow-sm sm:p-7" aria-label="FAQ response">
            <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.12em] text-oxblood">
              <Sparkles aria-hidden="true" className="h-4 w-4" /> Archive guide
            </div>
            <h2 className="mt-4 font-serif text-xl font-semibold leading-snug">{selectedFaq.question}</h2>
            <p className="mt-4 min-h-24 text-base leading-8 tracking-[0.015em] text-ink/85" aria-live="polite" aria-atomic="true">
              {selectedFaq.answer.slice(0, visibleLength)}
              {visibleLength < selectedFaq.answer.length && <span aria-hidden="true" className="typing-caret ml-0.5 inline-block h-5 w-0.5 translate-y-1 bg-oxblood" />}
            </p>
            <a
              href={selectedFaq.url}
              target="_blank"
              rel="noreferrer"
              className="mt-auto inline-flex w-fit items-center gap-2 pt-5 text-sm font-semibold text-oxblood underline underline-offset-4"
            >
              <BookOpen aria-hidden="true" className="h-4 w-4" /> {selectedFaq.source}
              <ExternalLink aria-hidden="true" className="h-3.5 w-3.5" />
            </a>
          </article>
        </section>

        <aside className="rounded-xl border border-oxblood/25 bg-[#F5E8E8]/60 p-5 sm:p-6">
          <h2 className="font-serif text-lg font-semibold">AI assistant: planned for a future implementation</h2>
          <p className="mt-2 text-sm leading-relaxed text-ink/75">
            This prototype guide uses a small set of reviewed FAQs. A more advanced assistant, capable of broader source-grounded research tasks, is under process and planned for future implementation.
          </p>
        </aside>
      </main>
    </div>
  );
};
